name: Auto Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/cli-action@v2

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: Merge Pull Request Automatically
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --auto --merge
