name: Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR creation or update

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli@v3

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge ${{ github.event.pull_request.number }} --repo ksnarkhede/Automata --auto --merge
