name: PR Created - GitHub CLI Example

on:
  pull_request:
    types: [opened, synchronize]  # Trigger the workflow when a PR is created or updated

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive.key | sudo tee /etc/apt/trusted.gpg.d/githubcli.asc
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI with PAT
        run: gh auth login --with-token ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create a PR-related issue
        run: |
          pr_title=$(jq --raw-output .pull_request.title $GITHUB_EVENT_PATH)
          pr_url=$(jq --raw-output .pull_request.html_url $GITHUB_EVENT_PATH)
          gh issue create --title "Issue related to PR: $pr_title" --body "This issue is related to PR: $pr_url"


      - name: logout
        run: gh auth logout
