name: Enable Auto-Merge for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enable_auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          gh-version: 'latest'
          
      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        
      - name: Enable Auto-Merge for PR
        run: |
          REPO_NAME="ksnarkhede/Automata"
          PR_NUMBER=$(gh pr view --repo $REPO_NAME --json number -q .number)
          gh pr merge $PR_NUMBER --repo $REPO_NAME --auto --merge --delete-branch
